# Generated by Django 4.1.1 on 2023-08-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_lesson_options_student_isonline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="lesson_data",
        ),
        migrations.RemoveField(
            model_name="student",
            name="isonline",
        ),
        migrations.AddField(
            model_name="lesson",
            name="day",
            field=models.CharField(default="monday", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="isonline",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lesson",
            name="time",
            field=models.TimeField(default="00:00"),
            preserve_default=False,
        ),
    ]
