# Generated by Django 4.1.1 on 2023-08-04 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_register"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.student"
            ),
        ),
    ]
