# Generated by Django 4.1.1 on 2023-08-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_lesson_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="lessons_remaining_grammar_only",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="lessons_remaining_native_only",
            field=models.IntegerField(default="0"),
            preserve_default=False,
        ),
    ]
